spring:
  application:
    name: blog-agent
  ai:
    mcp:
      client:
        stdio:
          connections:
            brave-search-mcp:
              command: npx.cmd
              args:
                - -y
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}

blog-agent:
  output-dir: blog-posts
  number-of-keywords: 5

embabel:
  agent:
    platform:
      models:
        openai:
          api-key: ${OPENAI_API_KEY}
    logging:
      personality: starwars
#  models:
#    default-llm: claude-sonnet-4-6
#    llms:
#      reviewer: claude-opus-4-6
  models:
    default-llm: gpt-5-mini
    llms:
      reviewer: gpt-5